version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "04:00" # 13:00(UTC+9)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: daily
      time: "04:00" # 13:00(UTC+9)
    ignore:
      - dependency-name: "chromedriver-binary"
