[project]
name = "asken-exporter"
version = "0.1.0"
description = "Prometheus exporter for Asken"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "prometheus-client>=0.21.1",
    "pyvirtualdisplay>=3.0",
    "pyyaml>=6.0.2",
    "selenium>=4.28.0",
]
