[project]
name = "asken-exporter"
version = "0.1.0"
description = "Prometheus exporter for Asken"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "prometheus-client",
    "pyvirtualdisplay",
    "pyyaml",
    "selenium",
]
