global:
  scrape_interval:     15s 
  evaluation_interval: 15s 
  external_labels:
      monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: /asken.prom
    static_configs:
      - targets:
        -  asken-exporter:80
