name: Check Browser Version

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0/6 * * * *'

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:

      - name: Check Out Repo
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      - name: Check Browser Version
        run: |
          browser_version=$(google-chrome --version | sed -e 's/Google Chrome //g' | sed -e 's/ //g')
          echo "browser_version=${browser_version}" >> $GITHUB_ENV

      - name: Check Library Version
        run: |
          library_version=$(cat Pipfile | grep "chromedriver-binary" | sed -e 's/chromedriver-binary = "==//g' | sed -e 's/.0"//g')
          echo "library_version=${library_version}" >> $GITHUB_ENV
      
      - name: Check, Replace
        run: |
          if [ "${browser_version}" != "${library_version}" ]
          then
            branch_name="update-to-${browser_version}"
            echo "branch_name=${branch_name}" >> $GITHUB_ENV
            
            git checkout -b "update-to-${browser_version}"
            sed -i "s/${library_version}/${browser_version}/g" Pipfile
            pipenv update

            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --global user.name "GitHub Action"
            git commit -am"Update chromium-driver to ${browser_version}"
          else
            exit 0
          fi
      - name: make PullRequest
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "master"
          source_branch: "${{ env.branch_name }}"
          github_token: ${{ secrets.GITHUB_TOKEN }}
