name: Check Browser Version

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0/6 * * * *'

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:

      - name: Check Out Repo
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      - name: Check Browser Version
        run: |
          browser_version=$(google-chrome --version | sed -e 's/Google Chrome //g' | sed -e 's/ //g')
          echo "browser_version=${browser_version}" >> $GITHUB_ENV

      - name: Check Library Version
        run: |
          library_version=$(cat Pipfile | grep "chromedriver-binary" | sed -e 's/chromedriver-binary = "==//g' | sed -e 's/.0"//g')
          echo "library_version=${library_version}" >> $GITHUB_ENV
      
      - name: Check, Replace
        run: |
          set -eux
          if [ "${browser_version}" != "${library_version}" ]
          then
            sed -i "s/${library_version}/${browser_version}/g" Pipfile
            pipenv update
          else
            exit 0
          fi
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          delete-branch: true
          title: Update chromium-driver to ${{ env.browser_version }}
