name: Upload Asken prom data

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo 
      uses: actions/checkout@v3
    - uses: nanasess/setup-chromedriver@v1.0.5
    - name: Install pipenv
      run: pipx install pipenv
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
        cache: pipenv
    - name: Install dependencies
      run: pipenv install
    - name: Start XVFB
      run: Xvfb :99 &
    - name: Run Gathering Asken Data
      run: pipenv run main
      env:
        DISPLAY: :99
        ASKEN_USERNAME: ${{ secrets.ASKEN_USERNAME }}
        ASKEN_PASSWORD: ${{ secrets.ASKEN_PASSWORD }}
        TZ: ${{ secrets.TZ }}
    - name: setup GCP Auth
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    - name: setup GCP project information
      uses: google-github-actions/setup-gcloud@v0
    - name: Upload JSON to GCS
      uses: google-github-actions/upload-cloud-storage@v0
      with:
        path: ./container/public/asken.prom
        destination: ${{ secrets.BUCKET_NAME }}/
    - name: Update Prometheus Data in RaspberryPi
      uses: benc-uk/workflow-dispatch@v1
      with:
        repo: legnoh/life-metrics-grafana-deployment
        ref: refs/heads/main
        workflow: Get Latest Metrics Data from GCS
        token: ${{ secrets.PERSONAL_TOKEN }}
