name: publish

on:
  push:
    branches:
    - main
    paths-ignore:
    - '.github/**'
    - '.vscode/**'
    - '.example.env'
  workflow_dispatch:

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:

      - name: Check Out Repo 
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Install pipenv
        run: pipx install pipenv
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate requirements.txt
        run: pipenv requirements > requirements.txt

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/asken-exporter:latest

      # - name: Restart Docker on RaspberryPi
      #   uses: benc-uk/workflow-dispatch@v1.2.2
      #   with:
      #     repo: legnoh/life-metrics-grafana-deployment
      #     workflow: Reset docker-compose setting
      #     token: ${{ secrets.PERSONAL_TOKEN }}
